### ISSUE TITLE
Building rdkafka library with openssl 1.1.x

### ISSUE THREAD

**Issue by nouzun** [edenhill/librdkafka#1618]
Is there a way to use openssl 1.1.x instead of openssl 1.0.2 for windows rdkafka library? 

I tried to link with 1.1.0 but it give errors live below during the build operation.

> librdkafka\src\rdkafka_transport.c(430): error C2065: 'CRYPTO_LOCK': undeclared identifier

**Comment by edenhill** [comment]
Sorry no, Only the LTS 1.0 series of OpenSSL is currently supported.

**Comment by edenhill** [comment]
Is there something in OpenSSL 1.1 that you need that is not available in 1.0?

**Comment by nouzun** [comment]
Not really, but I'm using rdkafka library in another project and it already uses openssl 1.1.0 and I don't want to mix two version of openssl in the same project. Could you guess how much effort would it take if I try to make it compatible with openssl 1.1? 
Thank you!

**Comment by edenhill** [comment]
No idea really, haven't looked much at 1.1, but if you are willing to do the work and submit a PR that has support both for 1.0 and 1.1 then that'd be great.

This might be a start: https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes

**Comment by raulbocanegra** [comment]
Hi @nouzun, have you tried to link against the windows crypt32 library?
Probably 
https://github.com/edenhill/librdkafka/commit/9363168cf3e4914e26ba1a129cb9d203e85cf07b fix your issue if you use static libs and CMake.

**Comment by LighthouseJ** [comment]
I think that I've been able to get librdkafka, compile, statically link and work with openssl 1.1.0g with at least rdkafka_example, but I get a crash in rdkafka_example_cpp.
I've been trying to use librdkafka via conan and I have a PR out against the conan package repo provider.
Original conan package: https://github.com/ess-dmsc/conan-librdkafka
My PR: https://github.com/ess-dmsc/conan-librdkafka/pull/4
That PR enables the conan recipe to build examples and tests on Linux only.

If the options are turned on, it links to zlib 1.2.11 and openssl 1.1.0g
Compiling using gcc 6.2.0, MSVC 2015

**Comment by mxk1235** [comment]
no SASL is not needed for SSL, their support in librdkafka can be added independently of each other.

**Comment by nouzun** [comment]
I'm able to build it with OpenSSL 1.1.0 with these changes:

https://github.com/nouzun/librdkafka/commit/991eaf652966d0e1b1da637387e087df9c777fc2

**Comment by edenhill** [comment]
related: https://github.com/edenhill/librdkafka/pull/2000
