### ISSUE TITLE
librdkafka producer and TLS1.3

### ISSUE THREAD

**Issue by laurafbec** [edenhill/librdkafka#3342]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
Hi everyone,
I've configured my kafka server in order to work with TLSv1.3, I've no problems when using the kafka-console-producer and kafka-console-consumer tools, but when using my librdkafka producer, I've got the error

%3|1617986440.624|FAIL|rdkafka#producer-1| [thrd:ssl://localhost:9093/bootstrap]: ssl://localhost:9093/bootstrap: SSL handshake failed: s23_clnt.c:794: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (after 4ms in state CONNECT)
%7|1617986440.624|STATE|rdkafka#producer-1| [thrd:ssl://localhost:9093/bootstrap]: ssl://localhost:9093/bootstrap: Broker changed state CONNECT -> DOWN

I have openssl 1.1.1g

How should I configure my client?
Thanks in advance!

How to reproduce
================
<your steps how to reproduce goes here, or remove section if not relevant>

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): v1.6.1
 - [x] Apache Kafka version: 2.13-2.7.0
 - [x] librdkafka client configuration: security.protocol="ssl", ssl.ca.location=<..>, ssl.certificate.location=<...>
 - [x] Operating system: Ubuntu 16.04
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by laurafbec** [comment]
I'm cheking the ciphers suites and, although they works with openssl 

~$ openssl s_client -connect localhost:9093 -ciphersuites TLS_AES_128_GCM_SHA256 -tls1_3
CONNECTED(00000003)

I get the following error with my client

%7|1617988299.586|OPENSSL|rdkafka#producer-1| [thrd:app]: librdkafka built with OpenSSL version 0x1000207f
%7|1617988299.594|SSL|rdkafka#producer-1| [thrd:app]: Setting cipher list: TLS_AES_128_GCM_SHA256
Failed to create producer: ssl.cipher.suites failed: ssl_lib.c:1380: error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match

**Comment by laurafbec** [comment]
Solved!! I've forgotten to build rdkafka with the new openssl version!! my mistake :D
