### ISSUE TITLE
Compile on Mac

### ISSUE THREAD

**Issue by gpatmore** [edenhill/librdkafka#49]
Can you give any insight on overcoming errors below when trying to make on Mac?

cc -MD -MP -O2 -Wall -Werror -Wfloat-equal -Wpointer-arith -fPIC -I. -g -DSG -c rdkafka.c
rdkafka.c:1065:29: error: use of GNU old-style field designator extension [-Werror,-Wgnu-designator]
        struct consume_ctx ctx = { consume_cb: consume_cb, opaque: opaque };
                                   ^~~~~~~~~~~
                                   .consume_cb = 
rdkafka.c:1065:53: error: use of GNU old-style field designator extension [-Werror,-Wgnu-designator]
        struct consume_ctx ctx = { consume_cb: consume_cb, opaque: opaque };
                                                           ^~~~~~~
                                                           .opaque = 
2 errors generated.
make: **\* [rdkafka.o] Error 1

**Comment by Kentzo** [comment]
I came across this issue when googling for the following error: Assertion failed: (!"Unknown operand"), function LinkLocation, file /SourceCache/dwarf_utilities/dwarf_utilities-114/source/DWARFdSYM.cpp, line 1704.

Here is the solution: https://gist.github.com/Kentzo/e038118346f1e1a582ac

**Comment by edenhill** [comment]
Thanks @Kentzo

**Comment by kparadkar** [comment]
@edenhill I am running on El Capitan Mac OSX 10.11.16 but I am unfortunately stuck on 0.9.1. 
I downloaded 0.9.1 code from your when I try to compile (using make) I get 'openssl/ssl.h' not found error. (I noticed that you have WITH_SSL flag set to 'y' in 0.9.1 and it is 'n' in master in Makefile.config)

Since I was getting those errors (I didn't want to make changes to code I got from your repo) I installed openssl on MAC (irrespective of BUG [Dont use OpenSSL on OSX #408](url)). And now I get following errors:
Undefined symbols for architecture x86_64:
  "_OPENSSL_init_crypto", referenced from:
      _rd_kafka_transport_ssl_init in rdkafka_transport.o
  "_OPENSSL_init_ssl", referenced from:
      _rd_kafka_transport_ssl_init in rdkafka_transport.o
  "_TLS_client_method", referenced from:
      _rd_kafka_transport_ssl_ctx_init in rdkafka_transport.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

So i have couple of questions here: 
1. I dont need openssl for my test code, then shouldn't library compile irrespective of presence of openssl/ssl.h? 
2. Do you have any idea about why I still get errors even after installing openssl?
3. Why does master say WITH_SSL = n ? I noticed that the bug #408 was reported on Nov3rd 2015 and release date of 0.9.1 was May23rd 2016, so is there any other reason for keeping openssl in 0.9.1 but remove from 0.9.2 ?

Please help as I have to get this library to compile on 0.9.1 !

Thank you.

**Comment by edenhill** [comment]
You need to pull in this commit to make ./configure correctly detect OpenSSL on OSX, or actually not to detect it, but doing that properly.

https://github.com/edenhill/librdkafka/commit/2add32d58713c38f4dc256828540b6e476f56b88

**Comment by kparadkar** [comment]
After pulling this commit, now make complains about SSL_CTX
./rdkafka_conf.h:90:3: error: unknown type name 'SSL_CTX'
                SSL_CTX *ctx;

If I understand correctly from the code this is all conditional for WITH_SSL = y. 
What am I missing here exactly? since include 'openssl/ssl.h' succeeded ?

**Comment by edenhill** [comment]
That looks very weird.
If openssl/ssl.h is found it should be able to commit.
Maybe you are on a incompatible version of OpenSSL?
librdkafka supports 1.0.x, not 1.1.x

**Comment by barracuda156** [comment]
> I came across this issue when googling for the following error: Assertion failed: (!"Unknown operand"), function LinkLocation, file /SourceCache/dwarf_utilities/dwarf_utilities-114/source/DWARFdSYM.cpp, line 1704.
> 
> Here is the solution: https://gist.github.com/Kentzo/e038118346f1e1a582ac

@Kentzo Do you know what commit specifically fixed that in dsymutil?

The bug is also showing up on 10.6:
https://trac.macports.org/ticket/65291
https://trac.macports.org/ticket/69188
