### ISSUE TITLE
Librdkafka does not compile on OSX 10.8.5

### ISSUE THREAD

**Issue by xiaojun789** [edenhill/librdkafka#33]
Hi
   I try to build the library in my Mac, but it failed. My mac info is:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin12.5.0
Thread model: posix
```

the error message is:

```
cc -MD -MP -O2 -Wall -Werror -Wfloat-equal -Wpointer-arith -fPIC -I. -g -DSG -c rdkafka.c
rdkafka.c:1064:29: error: use of GNU old-style field designator extension [-Werror,-Wgnu-designator]
        struct consume_ctx ctx = { consume_cb: consume_cb, opaque: opaque };
                                   ^~~~~~~~~~~
                                   .consume_cb = 
rdkafka.c:1064:53: error: use of GNU old-style field designator extension [-Werror,-Wgnu-designator]
        struct consume_ctx ctx = { consume_cb: consume_cb, opaque: opaque };
                                                           ^~~~~~~
                                                           .opaque = 
2 errors generated.
make: *** [rdkafka.o] Error 1
```
