### ISSUE TITLE
Can't build on rhel4 with gcc346 or 4.1

### ISSUE THREAD

**Issue by winbatch** [edenhill/librdkafka#76]
Long story as to why I need to build there, but getting this.  Any idea?

gcc4 -MD -MP -O2 -Wfloat-equal -Wpointer-arith -I. -g -DSG -fPIC -c rdkafka_broker.c

rdkafka_broker.c: In function ârd_kafka_broker_buf_enq0â:

rdkafka_broker.c:499: error: expected expression before âelseâ

rdkafka_broker.c: In function ârd_kafka_broker_producer_serveâ:

rdkafka_broker.c:2168: warning: initialization makes pointer from integer without a cast
